name: ci


on:
  push:
  pull_request:
  workflow_call:  # To make this workflow reusable.
  workflow_dispatch:  # To enable this workflow to be manually triggered.


jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true  # https://docs.astral.sh/uv/guides/integration/github/#caching

      - name: Set up pinned Python version
        run: uv python install

      - name: Set up project
        run: uv sync --group dev

      - name: Run tests
        run: uv run pytest --cov=mock --cov-report=xml tests/

      - uses: codecov/codecov-action@v5
        with:
          verbose: true
