name: ci

# Triggers the workflow on push or pull request events
on:
- push
- pull_request
- workflow_dispatch  # Allows running this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Set up project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest --cov=mock --cov-report=xml tests/

      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
